### ISSUE TITLE
Nit: Different label for the BOM drop down menu?

### ISSUE THREAD

**Issue by parkjam4** [GoogleCloudPlatform/cloud-code-intellij#2050]
Looking at the Add Google Cloud Libraries page, the BOM selector label says Google Cloud Libraries Version.
It sounds like you are selecting the version number of the cloud client libraries instead of selecting the version of the BOM you want to use. Could be a little confusing.
Could be better to say Select BOM version:

**Comment by etanshaul** [comment]
we actually did this on purpose. the idea being that most users may not know what a BOM is. We are, in a away, selecting the version of the client library since that version there itself controls the version of the client library.

Open to suggestions though. Maybe something like "Google Cloud Libraries Version (BOM)".

**Comment by parkjam4** [comment]
Or perhaps "Google Cloud Libraries BOM Version"

**Comment by etanshaul** [comment]
I think that may have the same problem (of users not understanding what a BOM is). @patflynn @ivanporty @nbashirbello if anyone has opinions on this

**Comment by etanshaul** [comment]
Cloud Cloud Java: 0.42.0-alpha (BOM)
                                0.41.0-alpha (BOM)'

plus link to google-cloud-java github versioning docs.

**Comment by jmah-cc** [comment]
This area was re-design, not relevant any more.
