### ISSUE TITLE
Run on local server goes into "Other" menu item on Linux

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2176]
The following can be seen on Linux:

![other-menu-item](https://user-images.githubusercontent.com/11686100/41550874-12f6c108-72f8-11e8-8896-4c4c0b3378c8.png)

Note: this is not happening on Mac OS for some reason.

The following is printed into the log:
```
2018-06-18 12:56:22,394 [   2815]  ERROR - nSystem.impl.ActionManagerImpl - com.google.cloud.tools.intellij.appengine.java.ultimate.server.run.AppEngineStandardLocalRunToolsMenuAction (GoogleCloudTools.AppEngineStandardLocalRun): 
group with id "GoogleCloudTools.AppEngine" isn't registered; action will be added to the "Other" group [Plugin: com.google.gct.core] 
com.intellij.diagnostic.PluginException: com.google.cloud.tools.intellij.appengine.java.ultimate.server.run.AppEngineStandardLocalRunToolsMenuAction (GoogleCloudTools.AppEngineStandardLocalRun): group with id "GoogleCloudTools.AppEngine" isn't registered; action will be added to the "Other" group [Plugin: com.google.gct.core]
```

**Comment by etanshaul** [comment]
It likely due to the ordering in which we declare the dependencies in plugin.xml. 

The key here is that the group id definition (defined in the core module's plugin.xml) gets loaded before the action that gets added to the group; if not, the platform will drop it under "other". The thing that confuses me is why does this only happen for the local run action. Other actions, like cloud libraries, are defined in the same relative order as local run.

**Comment by etanshaul** [comment]
@ivanporty are you still seeing this happen on master? I'm not

**Comment by ivanporty** [comment]
not happening for me either, confirmed.

**Comment by etanshaul** [comment]
reopening - this is still happening (unpredictably still it seems.). More crucially, however, is that in the recently released IDEA 2018.3, this "error" is now bubbled up to an IDE error. So it shows up in the normal exception reporting mechanism.

**Comment by etanshaul** [comment]
see https://youtrack.jetbrains.com/issue/IDEA-203089

**Comment by etanshaul** [comment]
fixed in 2019 and we have a workaround implemented
