### ISSUE TITLE
Support switching kubectl context/cluster per run configuration

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2370]
It could be useful to support specific cluster (kubectl context) for a run configuration, in order to support fine-grained configurations to deploy and test in a local cluster (minikube or docker) vs. remote GKE cluster without having to check which cluster is active now and switching it manually.

Possible ways to do this:
* Call `kubectl config set-context` before deployment. This changes the global context after each run.
* Use Skaffold support and pass `--context` to `kubectl` command to deploy to specified cluster.
Related Skaffold issue: https://github.com/GoogleContainerTools/skaffold/issues/511

**Comment by etanshaul** [comment]
Was just testing out the, currently read-only, cluster target in the run configuration (which is great btw), and I was thinking:

When support switching the cluster context for the user we have a couple options:
1) Pin a run configuration permanently to a certain cluster (if it remains available) and then, regardless of the externally configured active cluster, we switch to this cluster every time.
2) The cluster dropdown, whenever the run config is opened, defaults to just display the active cluster. So the selection could switch if the user sets the active cluster externally for example.

I am more in favor of (1) since its more predicable and could lead to less mistakes. But we should align with vscode (who I think is also doing something like (1)).

@matthewmichihara

**Comment by matthewmichihara** [comment]
Aligning with what whatever vscode is doing makes sense to me.

If we go with 1, I'd vote for using the skaffold `--context` flag that Ivan mentioned.

**Comment by ivanporty** [comment]
I think the run configuration abstraction pairs perfectly with a pretty broad state, and having an option to set a specific cluster / namespace for it was something we were thinking about long time ago - imagine targets for `test on GKE / QA namespace`, `test on Docker cluster`, `deploy to AWS staging` - this is convenient.

I suspect skaffold team has not yet decided on support of context switching, so we may need to go with setting the active cluster ourselves, but keeping the current active cluster and having an ability to deploy to a different one would be less intrusive.

**Comment by matthewmichihara** [comment]
Ah I didn't realize the `--context` flag doesn't actually exist. Those sample run configurations you mentioned do sound like they'd be really useful.

**Comment by etanshaul** [comment]
> I suspect skaffold team has not yet decided on support of context switching, so we may need to go with setting the active cluster ourselves, but keeping the current active cluster and having an ability to deploy to a different one would be less intrusive.

Agree. Although I think Skaffold does do what I stated in (1). Then pin a skaffold command to a specific cluster (and then manually change contexts using kubectl).

**Comment by matthewmichihara** [comment]
Current direction I'm going with the UI --

Normal context selection:
![image](https://user-images.githubusercontent.com/79073/56535736-6cce4500-652a-11e9-8304-e26810770ee0.png)

Previous saved context no longer exists (deleted from kubeconfig):
![image](https://user-images.githubusercontent.com/79073/56588785-0d1b7c80-65b2-11e9-8b1a-4ecef63299de.png)
