### ISSUE TITLE
Gradually reduce Skaffold appearance in the UI and text across the plugin

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2451]
Instead, emphasize Kubernetes support without mentioning underlying tools and stack.

**Comment by ivanporty** [comment]
I think this is quite straightforward change now since we are officially Cloud Code now.
For run targets general name, I guess it is one of:
* `Cloud Code Deploy` 
* `Cloud Code: Kubernetes`
* `Kubernetes with Cloud Code` 

and for dev / deploy targets we can either still use our Kubernetes names, or use:
* `Continuous Deploy` and `Deploy` similar to VS Code one.
* `Continuous Deploy to Kubernetes` and `Deploy to Kubernetes`

@etanshaul WDYT?

**Comment by etanshaul** [comment]
First I'd say that since we have more support than just Kubernetes (i.e. app engine), and generic "Deploy" or event "Cloud Code Deploy" naming would be confusing. I think we must have the word "Kubernetes" in there.

I think your suggestion of `Continuous Deploy to Kubernetes` and `Deploy to Kubernetes` is nice. It solves the problem I stated above, while keeping it aligned with VS Code too.

**Comment by etanshaul** [comment]
or even:

`Kubernetes Continuous Deploy`
`Kubernetes Deploy`

**Comment by ivanporty** [comment]
Agree on the last one, even easier. Cool, I'll whip up a quick PR with screenshots and we'll discuss further.
