### ISSUE TITLE
CustomResource support in IDE

### ISSUE THREAD

**Issue by tanner-bruce** [GoogleCloudPlatform/cloud-code-intellij#2545]
**What did you do?**

Edited the YAML for a custom resource

**What did you expect to see?**

The plugin to use the OpenAPI spec from the apiserver on my current context to properly complete CustomResources

**What did you see instead?**

![image](https://user-images.githubusercontent.com/21345430/57390218-7211cd80-7181-11e9-9011-2936abcce303.png)

Aside: where is the source code for this plugin? Based on the commit history it used to be here but I am unable to find the new location.

**Comment by etanshaul** [comment]
Hi @tanner-bruce thanks for issue report. We don’t yet have CRD editing support in the plugin but it will be coming soon. Regarding the errors: do you have the JetBrains Kubernetes plugin installed? That plugin provides K8s resource editing support and it is likely that it is not recognizing your CRD. In 2019.1 it added ability to manually point to OpenApi specs for your resources which may resolve this.

And lastly regarding the source. After our recent rebrand and expanded Kubernetes support we moved the source to a private repo so that we can focus on creating a great experience. Once we are ready to accept contributions we will revisit this.

**Comment by jmah-cc** [comment]
We're working on enhancing support for popular CRDs in an upcoming release

**Comment by axmerc** [comment]
Hi @tanner-bruce This should work now if you have it installed in the current context. Please reopen if it doesn't!
