### ISSUE TITLE
Update `kubectl.fail` event

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2553]
I noticed that we have an event called `kubectl.fail` that shows a `ProcessExecutionException` in the metadata.

I think we need to update the event so that its specific to the action; i.e., what failed here? If it was listing contexts, it should be something like `kubernetes.context.listing.failed`, with metadata that indicates why (e.g. `kubectl` is not installed).

This is related to #2549

**Comment by etanshaul** [comment]
@matthewmichihara if you have time to check out this one

**Comment by etanshaul** [comment]
@matthewmichihara any update on this one? (i'm doing a one-over on our 19.6.1 milestone. feel free to unassign if you have too many issues, and I'll redistribute).

**Comment by matthewmichihara** [comment]
No updates but will look into this today.

**Comment by matthewmichihara** [comment]
If we want to update the event name based on the action performed (`kubernetes.context.listing.failed`, `kubernetes.pod.listing.failed`, etc), I think we need to move the event logging up a level of abstraction from `KubectlExecutorService` to `KubectlApi`, adding logging event names to each of the different `kubectl` actions (`KubectlApi#getConfig`, `KubectlApi#getPods`, etc).

Or, I think we could also keep the logging where it is, and continue using a somewhat generic `kubectl.fail` event name, but additionally log the command line args so that we'd know what is failing.

It sounds like we want the first option right @etanshaul ?

**Comment by etanshaul** [comment]
yes, I think the former makes sense. Its strange that we have this lone `kubectl.fail` event. This doesn't mirror what we are doing for Skaffold.

**Comment by matthewmichihara** [comment]
Yeah. On a broader note, I do wish that the skaffold service and kubectl service were more unified.

**Comment by sageprice** [comment]
> Yeah. On a broader note, I do wish that the skaffold service and kubectl service were more unified.

I'm curious what this would look like (mainly since we'll have to run more commands soon to install things, and maybe in future interact with Kubernetes or various cloud APIs directly). Would this mean pushing more logic into the `CommandExecutor` for generic command execution logic? or are there things common to skaffold and kubectl which would be nice to have in another layer?

**Comment by matthewmichihara** [comment]
Perhaps. To me, both classes are just wrappers around command line programs that could share a bit more code. For example, `KubectlExecutorService` will always first check if `kubectl` is available before executing a command, vs `SkaffoldExecutorService`, which relies on the caller to do so but I think there's no reason both couldn't handle this the same way.

**Comment by matthewmichihara** [comment]
Updating this issue after some offline discussion --

We have a list of events we want to log [here](https://docs.google.com/spreadsheets/d/1XSOIajPXin5WdiKlMvuXK3l8hnjVK14rry0WISY_8_k/edit#gid=0). They are all very closely tied to user interaction (ie user refreshes explorer, user does a deploy). We should aim to align with these metrics 1. for consistency with vscode and 2. because it is difficult to figure out the context of these method calls otherwise since they are used by multiple actions.

Given this, I think the path forward here is replacing these logging calls at the `KubectlExecutorService` level with ones tied to user interactions. For this `kubectl.fail` event in particular, we should add logging to the kubernetes explorer and deployment code to capture areas where we are interacting with kubectl. @ivanporty @etanshaul does this sound right?

**Comment by ivanporty** [comment]
Sure, this is more unified approach, although your track function was a great start - we would have all kubectl actions measured instantly.
Could we keep the general track function in simple cases like this - success and failure_reason with exception name?
also, about VS Code - are we sure they actually use the different event names for example for setting context when deployment action is called vs. setting context from k8s explorer? Their metrics are heavily based around "commands" and seem to be not that fine grained.

**Comment by matthewmichihara** [comment]
My hesitation with adding the logging in `KubectlApi` is that I didn't want to add a maintenance / code clarity burden just for intellij-specific logging that I'm not sure anyone is really going to look at. My current philosophy is to try to keep the logging to a minimum but could be convinced otherwise.

Regarding setting the active context - it looks like they log it when its done in the explorer, and indirectly via deployment success/fail events they track.

**Comment by matthewmichihara** [comment]
Can this work be folded into the upcoming metrics alignment work or is this something we want asap? @etanshaul

**Comment by etanshaul** [comment]
From the discussion it sounds like that work is a prerequisite to this, so it makes sense I think to do that first.

@ivanporty since you are working on the gcloud metrics piece, does it make sense for @matthewmichihara tackle the alignment implementation starting with Skaffold, then using that pattern for `kubectl`? iirc, we have decided how to proceed with the alignment of Skaffold events.

**Comment by etanshaul** [comment]
Summarize offline discussion:

send metadata as part of deploying - boolean indicating if the active context was changed.

separately instrument opening / applying of run config

**Comment by matthewmichihara** [comment]
- instrumenting when the active context was changed during a run is done
- remaining work for this milestone tracked in https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/237
- future instrumentation related investigations tracked in https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/239
