### ISSUE TITLE
IntelliJ Cloud Code Plugin - Debugging mode not working (Java)

### ISSUE THREAD

**Issue by akdev1** [GoogleCloudPlatform/cloud-code-intellij#2575]
(Please ensure you are running the latest version of Cloud Cloud for IntelliJ with _Help > Check for Updates_.)

- Cloud Code for IntelliJ version: 19.5.3
- OS: macOS Mojave 10.14.4

**What did you do?**
Hit "Debug" button with "Kubernetes Continuous Deploy" run configuration

**What did you expect to see?**
Debugger to be attached and application launches in debug mode

**What did you see instead?**
Debugger does not get attached, I do see port forwarding to debug ports of 5005 and correct entry in the run process as shown in the attached screenshot but execution does not halt at specified breakpoints, application continues to run in normal/non debug mode. There are no warnings or exceptions in the console window, I'm using the sample Guestbook application as-is. also tried a new application using JIB and observed the same behavior.

(screenshots are helpful)
![Screen Shot 2019-06-02 at 6 23 49 PM](https://user-images.githubusercontent.com/5050474/58768628-dd25a880-8563-11e9-8db3-b9f1094dd342.png)

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by etanshaul** [comment]
hi @akdev1 thanks for reporting.

What version of Skaffold are you using? And what version of IntelliJ?

A few thing to try:

1) Upgrade to the latest version of Skaffold: https://github.com/GoogleContainerTools/skaffold/releases

2) Ensure that you have no runaway skaffold processes. To do this, check to find - and kill - processes running on port `50051`. Example on how to do this on Mac: https://stackoverflow.com/questions/3855127/find-and-kill-process-locking-port-3000-on-mac
`netstat -vanp tcp | grep 50051`
`kill -9 [pid]`

Note: this may be needed due to a bug that has been since fixed, but not yet released: #2554

3) You said you are running the guestbook app. Do you mean [this one](https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/master/java/java-guestbook)? If so make sure you pull the latest changes.

Please let us know if this helps.

**Comment by akdev1** [comment]
Thanks for your reply @etanshaul !

The issue was my specific version of intelliJ, I upgraded to the latest version 2019.1 from 2018.8 and the debugging is now working as it should.

Thanks for pointing me in the right direction.

**Comment by etanshaul** [comment]
thanks for the update @akdev1, and glad its working now! 

Just so we can make sure things are working as expected, what version were you using before? The plugin currently should support versions 2018.2 and up, so if debugging wasn't working properly there, we can investigate.
