### ISSUE TITLE
GoLand – Plugin "Google Cloud Tools" was not loaded: required plugin "org.jetbrains.idea.maven" not installed 

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/cloud-code-intellij#2589]
GoLand 2019.2 EAP
Build #GO-192.4787.18, built on June 6, 2019
GoLand EAP User
Expiration date: July 6, 2019
Runtime version: 11.0.3+12-b281.38 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
GC: ParNew, ConcurrentMarkSweep
Memory: 966M
Cores: 12
Registry: ide.completion.variant.limit=500, ide.mac.allowDarkWindowDecorations=true, suggest.all.run.configurations.from.context=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, izhangzhihao.rainbow.brackets

- Cloud Code for IntelliJ version:
- OS: Mac OS 10.14.5

**What did you do?**
Install Google Cloud Tools into GoLand

**What did you expect to see?**
Some help when I edit .yaml for kubernetes

**What did you see instead?**
Plugin "Google Cloud Tools" was not loaded: required plugin "org.jetbrains.idea.maven" not installed 

Jetbrains provides a wide range of IDE's, including Intellij, something called "Google Cloud Tools" should work with all of them.  Especially for working with Kubernetes yaml files.

**Comment by etanshaul** [comment]
hi @lesv 

Shorter answer:
If you just looking for yaml editing support for kubernetes files you can install the Jetbrains Kubernetes plugin: https://plugins.jetbrains.com/plugin/10485-kubernetes

Longer answer:
If you are looking to use the latest Google Cloud Code plugin (formerly called Google Cloud Tools) our release version does not yet support 2019.2 EAP. Our next release will span 2019.2. 

If you wanted to use Cloud Code now (to give you extra kubernetes support) you could download from our nightly channel to get the latest version (which does work with 2019.2 EAP): https://github.com/GoogleCloudPlatform/cloud-code-intellij#pre-releases (note to use `nightly` instead of `alpha`).

**Comment by lesv** [comment]
That works for me -- Thanks.
