### ISSUE TITLE
Cloud Code initialization

### ISSUE THREAD

**Issue by prary** [GoogleCloudPlatform/cloud-code-intellij#2680]
- Cloud Code for IntelliJ version: latest
- OS: Linux/Windows

**What did you do?**
Every time it finds the skaffold.yaml it tries to download dependencies even though kubectl and skaffold exists in path hence throws the error alert.
**What did you expect to see?**
It should first check in PATH and if not found then it should try to fetch from internet
**What did you see instead?**
Error alert in right bottom of intellij

**Comment by ivanporty** [comment]
Thanks for the report @prary 

Could you please double check the Cloud Code K8s settings (via general preferences / Cloud Code / Kubernetes), and see if you have manual or automatic dependencies selected? If you wish to use manually installed dependencies, you could always check the `Use Custom Dependencies` checkbox.

Let us know if this works.

**Comment by sageprice** [comment]
Thanks @prary for filing this. I wanted to +1 what @ivanporty said, but also try to address the motivation here. It seems like we've got two issues:

1. Feature request to change the default behavior for installing managed versions of skaffold/kubectl so it only installs when a dependency isn't present.
1. The installer failing for some unknown reason.

(1) seems more important so here's our thought process. We added managed dependency installation due to a number of difficulties users have run into when setting up or updating the plugin. One of those difficulties is that Cloud Code releases often rely on the latest version of skaffold, either for bug fixes or new features (some of which are backwards incompatible). Given that, we opted to have Cloud Code prefer to install separate versions of skaffold/kubectl even when you have a usable binary present on PATH. This ensures that the plugin can rely on our installed version so we can remove/update that version appropriately when a newer version of Cloud Code is installed (note -- we do not modify any binaries already on PATH, we do not mess with the environment), and so we know that the present versions of skaffold and kubectl work well together with our plugin.

However, Only installing when a needed version of skaffold/kubectl isn't on PATH sounds reasonable. I'd have to think about this more, it adds some complexity to the installation/execution behavior but sounds relatively safe. Personally, I'm hesitant b/c I'd worry about skaffold/kubectl getting out of sync in a way which is hard for the plugin to handle.

Regarding (2), we'd need a little more information to figure out what is breaking down here. Would you mind opening another issue with more detail about the failure you're seeing? In particular, what does the notification say/look like, and please [include IDE logs](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files) if possible.

**Comment by prary** [comment]
> Thanks for the report @prary
> 
> Could you please double check the Cloud Code K8s settings (via general preferences / Cloud Code / Kubernetes), and see if you have manual or automatic dependencies selected? If you wish to use manually installed dependencies, you could always check the `Use Custom Dependencies` checkbox.
> 
> Let us know if this works.

hi @ivanporty ,
Manual dependencies is selected and hence using custom dependencies.

**Comment by prary** [comment]
> (1) .... One of those difficulties is that Cloud Code releases often rely on the latest version of skaffold, either for bug fixes or new features (some of which are backwards incompatible). Given that, we opted to have Cloud Code prefer to install separate versions of skaffold/kubectl even when you have a usable binary present on PATH.

@sageprice that sounds great and perfectly make sense
> Regarding (2), we'd need a little more information to figure out what is breaking down here. Would you mind opening another issue with more detail about the failure you're seeing? In particular, what does the notification say/look like, what version of Cloud Code you are using, and please [include any relevant errors from the IDE logs](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files) if possible.

I am using intellij behind proxy which is the reason for download failing, connected the dots hence closing the issue.
