### ISSUE TITLE
Should Not Require a Dockerfile

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/cloud-code-intellij#2714]
- Cloud Code for IntelliJ version: 20.1.3
- Google Cloud SDK version: 280.0.0
- OS: Linux 5.2.17-1rodete3-amd64

**What did you do?**

Went to `Tools > Cloud Code > Kubernetes > Add Kubernetes Support`

**What did you expect to see?**

Kubernetes support added

**What did you see instead?**

It told me I needed to add a Dockerfile.  But my project can build a container using Jib or Buildpacks.

**Comment by etanshaul** [comment]
thanks @jamesward. A couple questions:

- is your project configured for Jib? (e.g. in `pom.xml` or `build.gradle`)
- which version of Skaffold are you currently using (you can check by going to Settings > Cloud Code > Kubernetes).
- Are you using a single or multi-service application? Currently our automatic bootstrapping is limited to single service applications, but mult-service is coming soon.

**Comment by jamesward** [comment]
Maybe I'm not understanding what the plugin is for.  My hope was that it'd allow me to right-click on a YAML in my project and be able to apply it to my cluster.  (Note that the Kubernetes explorer does work as expected.)

- This particular project is not using Jib.
- I'm not using Skaffold.
- Not sure what this means.

**Comment by etanshaul** [comment]
@jamesward sorry for that very late response. This one slipped by.

Currently we don't have support for applying individual YAMLs to the cluster (though this is a nice FR).

Rather, Cloud Code helps you get your application running on a Kubernetes cluster (rather than applying individual resource files). It does this using [Skaffold](https://github.com/GoogleContainerTools/skaffold) under the hood. Skaffold basically defines the artifacts that you are building, along with pointers to the Kubernetes manifests, (among other things). The plugin then takes care of building your application, pushing the image(s) to an image repository, applying any resources (`kubectl apply`), and watching for changes in your source code to propagate the changes to the cluster automatically.

Note: the original issue about needed a Dockerfile: if the project was configured to use Jib (e.g. the correct pieces in the `pom.xml`, the plugin wouldn't have complained about a missing Dockerfile.

Hopefully this helps a little bit. happy to provide more details. closing this issue for now.
