### ISSUE TITLE
Adding kubernetes to existing java project with jib fails

### ISSUE THREAD

**Issue by viniciusccarvalho** [GoogleCloudPlatform/cloud-code-intellij#2844]
(Please ensure you are running the latest version of Cloud Code for IntelliJ with _Help > Check for Updates_)
- Cloud Code for IntelliJ version: 20.10.1-202
- Google Cloud SDK version: 316.0.0
- OS: Mac OS X 10.15.7

**What did you do?**
Adding kubernetes support should create skaffold file 
**What did you expect to see?**
A new skaffold file
**What did you see instead?**
Nothing happened got error: ubernetes project not detected: Please ensure that you have Kubernetes resources in your project. You might also need to create a Dockerfile, or configure Jib for Java projects, so that your project can be containerized.
(screenshots are helpful)
_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by matthewmichihara** [comment]
Thanks for the report. Is this a result of clicking `Add Kubernetes Support` from the Cloud Code Tools menu? If possible, can you share a sample project that helps us reproduce this?

**Comment by viniciusccarvalho** [comment]
Hi Matthew, yes happened while trying to add it to an existing project from the tools menu. Here's the sample project: https://github.com/viniciusccarvalho/micronaut-graal-web

**Comment by matthewmichihara** [comment]
Thank you, I was able to reproduce the result you're seeing using that sample.

Cloud Code is only able to generate a Skaffold configuration for your project if it can find Kubernetes manifests in it, and it looks like this project does not have any, so that explains the error message.

I'm going to close since it looks like it is working as intended, but please let me know if I missed anything.
