### ISSUE TITLE
Cloud Code on pycharm doesn't watch for changes

### ISSUE THREAD

**Issue by yfried** [GoogleCloudPlatform/cloud-code-intellij#3020]
(Please ensure you are running the latest version of Cloud Code for IntelliJ with _Help > Check for Updates_)
- Cloud Code for IntelliJ version: 21.10.1
- Google Cloud SDK version: 363.0.0
- OS: Mac OS X 11.6

Pycharm version:
```
PyCharm 2021.2.3 (Professional Edition)
Build #PY-212.5457.59, built on October 19, 2021
Runtime version: 11.0.12+7-b1504.40 x86_64

macOS 11.6

Non-Bundled Plugins: com.intellij.ideolog (203.0.27.0), com.mnr.java.intellij.idea.plugin.base64helper (2.0.3), zielu.gittoolbox (212.7.15), de.netnexus.camelcaseplugin (3.0.8), org.jetbrains.plugins.go-template (212.5457.62), mobi.hsz.idea.gitignore (4.3.0), org.intellij.plugins.hcl (0.7.14), fr.alexisvisco.gitlablinks (1.2), com.intellij.kubernetes (212.5457.4), com.google.gct.core (21.10.1), izhangzhihao.rainbow.brackets (6.21)
```

**What did you do?**
 Run "Develop on Kubernetes"
**What did you expect to see?**
```
Deployments stabilized in ...
Port forwarding Deployment ...
Press Ctrl+C to exit
Watching for changes...
```
**What did you see instead?**
```
Deployments stabilized in ...
Port forwarding Deployment ...
Press Ctrl+C to exit
Not watching for changes...
```

When running `skaffold dev` locally, files are watched and synced as expected.

**Comment by etanshaul** [comment]
hey @yfried did you run in `run` or `debug` mode? I ask because currently watching is not available in `debug` mode (though it is coming very soon).

If you were in fact in `run` mode, could you please check the configuration settings, specifically this field:
<img width="664" alt="Screen Shot 2021-11-03 at 10 28 01 AM" src="https://user-images.githubusercontent.com/1735744/140079473-f88d45ea-699a-4aa9-8838-b4204b55afa6.png">

You want it to be set to "On source and configuration changes" so that we correctly configure Skaffold to watch for changes.

**Comment by yfried** [comment]
I tried both debug AND run. And with both auto-rebuild enabled and disabled.

I found out that adding the env var `SKAFFOLD_AUTO_SYNC=true` can fix this

**Comment by etanshaul** [comment]
Interesting. When you are in `run` mode, watching should be turned on as long as you have the setting above configured properly. 

If this is not the behavior you are observing, could you please share the full `skaffold dev` command line that is being executed? It will be near the top of the log output after hitting the `play` button. I want to confirm that the correct flags are set.

**Comment by yfried** [comment]
Apologies.
I checked now and it was set to Never.
Now it works as expected.

**Comment by etanshaul** [comment]
no problem. thank you for confirming.
