### ISSUE TITLE
Duet AI unexpected forced line break during autocompletion (when using soft-wrap).

### ISSUE THREAD

**Issue by andreas-timm** [GoogleCloudPlatform/cloud-code-intellij#3190]
<img width="748" alt="Screenshot 2024-03-11 at 11 38 59" src="https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/845878/95d5ae0b-c2c1-411b-a08f-3ecb046bc286">

### Expected Behavior

Display autocomplete without force line breaks.

### Actual Behavior

Line breaks occur in unexpected places, often several at a time, and this behavior changes dynamically as you continue typing. This makes using the Duet AI autocompletion feature almost impossible.

### Additional Information

- IDE type: WebStorm
- IDE version: 2023.3.4, Build #WS-233.14475.40, built on February 14, 2024
- Cloud Code version: 24.2.2-api-version-223
- Cloud SDK: not installed
- Operating System: macOS Sonoma, Version 14.4 (23E214)

**Comment by ivanporty** [comment]
Thanks for report @andreas-timm. We are looking into this. We saw other similar reports when there is an additional plugin(s) installed related to editing - do you have any editing plugins installed, such as Vim/Emacs?

**Comment by andreas-timm** [comment]
@ivanporty 
Thank you very much.
I reproduced this issue with an empty JetBrains profile without any other plugins.

**Comment by ivanporty** [comment]
I think you have "softwrap" enabled on this editor - I see the curved line icons at the end of each line and long lines are wrapped - what happens if you disable this?

<img width="334" alt="Screenshot 2024-03-13 at 5 59 05 PM" src="https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/11686100/5606ec73-6055-436f-a0a6-c93d0c0760c5">

**Comment by andreas-timm** [comment]
<img width="559" alt="Screenshot 2024-03-13 at 23 21 10" src="https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/845878/6659e36e-87d7-486a-b2b3-a8397fb4e9e8">

Yes, without "Soft-Wrap" enabled, lines are not wrapped (and the autocomplete suggestion is visible only partially).
This issue does not occur when "Soft-Wrap" is disabled.

**Comment by ivanporty** [comment]
Thanks for confirming @andreas-timm. We are working on a better completion integration deeper into IDE editing, and hopefully this will help with the issue here soon. I will update on the progress

**Comment by patkoscsaba** [comment]
I am so happy I found this. That wrapping was driving me crazy and actually making me disable the Duet AI. Many times the suggestions were quite good, but I effectively couldn't use them because of the apparent soft-wrapping (note: actual lines are not wrapped). 
Please address this issue, as from all the AI tools I tested so far, Duet (Gemini) seems to be the best for my needs.

**Comment by ivanporty** [comment]
We have a path to fix this, and we will update here when it's released.

**Comment by aav7fl** [comment]
@ivanporty Any news on when that might get released? The shifting of the page keeps forcing me to disable Gemini every time I want to write documentation in our apps. We rely on soft-wrap in our docs.

**Comment by ivanporty** [comment]
We just released completely reworked Gemini Code Assist functionality in the Cloud Code. It has native IDE completion support, no conflicts with other editor functionality, and your issue should be fixed, starting with version 24.8.1.
