### ISSUE TITLE
compilation inactive context awareness is off

### ISSUE THREAD

**Issue by aronsuarez** [GoogleCloudPlatform/cloud-code-intellij#3233]
### Expected Behavior
I will generate commit messages

### Actual Behavior
I can't generate commit messages, the Code Assist Plugin show this message: compilation inactive context awareness is off

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): Webstorm
- IDE version:  2024.2.2
- Cloud Code version (Settings > Plugins > Cloud Code):  24.8.2-233-IB.1-api-version-223
- Operating System: macos

https://github.com/user-attachments/assets/367672bf-9750-498a-bf5a-9ff52204a577

**Comment by ivanporty** [comment]
Thanks for the report @aronsuarez. The fix for this will be in the next release. For now, please try the following workaround to reset the settings: Open Gemini settings and set project id to empty, close settings. Open Gemini toolwindow, you should see the following:

<img width="468" alt="Screenshot 2024-09-25 at 5 11 50 PM" src="https://github.com/user-attachments/assets/6d16b677-ad5c-4fae-9812-6c94cba7a308">

Select project, and then click `Finish` (required to reset the context settings). Gemini should be active after that. Let us know if this worked for you.

**Comment by aronsuarez** [comment]
@ivanporty thank's this has worked
