### ISSUE TITLE
App Engine Local Server configuration screen doesn't handle smaller monitors

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/cloud-code-intellij#921]
<img width="1280" alt="screen shot 2016-09-22 at 7 22 06 am" src="https://cloud.githubusercontent.com/assets/7862557/18751845/60983ac4-8095-11e6-81d5-5e9d22199ebd.png">

If you look at this screenshot, I'm not able to scroll down to the apply/close buttons.

I reproduced this on a macbook bro 15 retina with IJ 2016.2.4

**Comment by joaoandremartins** [comment]
While I'm working on reproducing this, are you able to resize the window and, if so, do the buttons appear?

**Comment by patflynn** [comment]
I'm not super familiar with how os x windows work.  I can get the buttons
to appear by double clicking the title bar, but there's still no way to
expand the 'before launch' steps and still have the buttons visible.

**Comment by joaoandremartins** [comment]
@patflynn what resolution were you using?

**Comment by joaoandremartins** [comment]
Seems like I need to test this on a Mac, because on a Windows with 800x600 res, I can see the scroll bar, the buttons and the before launch tasks section size is normal.

**Comment by patflynn** [comment]
Not sure. Whatever res a macbook pro 13" is.  It did look like it could be
a mac specific issue.

**Comment by joaoandremartins** [comment]
Yeah, I'm trying this out on my Mac at low res, and it appears in many other windows, not just the run/debug one. Other windows allow for diagonal resize whereas ours doesn't. However, we don't have any control over the window GUI, since it's totally contained in the framework.

I'm a little out of ideas on how to solve this. I think the best we can do is to open an issue with IntelliJ asking them to enable diagonal resizing. We could also just reduce the amount of information we request, i.e., by hiding advanced settings in an elegant way if we think they can be hidden, and if I can find a better way of hiding them than I had before (the checkbox).

By the way, from what I've been reading online, the recommended way to deal with this is to press the green button on the top left corner, which zooms the window to the screen. I observed that this shows the buttons, but somehow no scroll bar ever appears. A scroll bar appears on other plaftorms (Linux and Windows), so I would think this is a Mac issue..

**Comment by patflynn** [comment]
OK. Thx Joao. I've been meaning to take a look at that configuration interface to see how it can be improved, but in the meantime I'm taking this bug off of the GA milestone.
